import AppKit

final class PasteboardMonitor: @unchecked Sendable {
    var onNewItem: ((ClipboardItem) -> Void)?

    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount
    private let lock = NSLock()
    private var isInternalWrite = false

    private let sensitiveBundleIDs: Set<String> = [
        "com.1password.1password",
        "com.1password.1password7",
        "com.agilebits.onepassword7",
        "com.bitwarden.desktop",
        "com.lastpass.LastPass",
        "com.dashlane.dashlanephonefinal",
        "org.keepassxc.keepassxc"
    ]

    func start() {
        stop()
        lastChangeCount = NSPasteboard.general.changeCount
        timer = Timer.scheduledTimer(withTimeInterval: 0.4, repeats: true) { [weak self] _ in
            self?.poll()
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    func performInternalWrite(_ work: () -> Void) {
        lock.lock()
        isInternalWrite = true
        lock.unlock()
        work()
        lastChangeCount = NSPasteboard.general.changeCount
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.25) { [weak self] in
            self?.lock.lock()
            self?.isInternalWrite = false
            self?.lock.unlock()
        }
    }

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount

        lock.lock()
        let skip = isInternalWrite
        lock.unlock()
        guard !skip else { return }

        if shouldSkipSensitive(pb) { return }

        let front = NSWorkspace.shared.frontmostApplication
        let appName = front?.localizedName
        let bundleID = front?.bundleIdentifier

        if let bid = bundleID, sensitiveBundleIDs.contains(bid) {
            return
        }

        if let str = pb.string(forType: .string), !str.isEmpty {
            // 极短且像密码的单行不记录（启发式，可关）
            if looksLikeSecret(str) { return }
            let item = ClipboardItem(
                id: UUID(),
                kind: .text,
                text: str,
                imageData: nil,
                createdAt: Date(),
                pinned: false,
                sourceAppName: appName,
                sourceBundleID: bundleID
            )
            DispatchQueue.main.async { self.onNewItem?(item) }
            return
        }

        if let image = NSImage(pasteboard: pb),
           let tiff = image.tiffRepresentation,
           let rep = NSBitmapImageRep(data: tiff),
           let png = rep.representation(using: .png, properties: [:]) {
            let item = ClipboardItem(
                id: UUID(),
                kind: .image,
                text: nil,
                imageData: png,
                createdAt: Date(),
                pinned: false,
                sourceAppName: appName,
                sourceBundleID: bundleID
            )
            DispatchQueue.main.async { self.onNewItem?(item) }
        }
    }

    private func shouldSkipSensitive(_ pb: NSPasteboard) -> Bool {
        guard let types = pb.types else { return false }
        let sensitive: [NSPasteboard.PasteboardType] = [
            .init("org.nspasteboard.ConcealedType"),
            .init("org.nspasteboard.AutoGeneratedType"),
            .init("com.apple.is-remote-clipboard"),
            .init("com.apple.security.password")
        ]
        return types.contains { sensitive.contains($0) }
    }

    private func looksLikeSecret(_ text: String) -> Bool {
        let t = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !t.contains("\n"), t.count >= 8, t.count <= 64 else { return false }
        // 无空格的高熵短串
        if t.contains(" ") { return false }
        let hasLetter = t.rangeOfCharacter(from: .letters) != nil
        let hasDigit = t.rangeOfCharacter(from: .decimalDigits) != nil
        let hasSymbol = t.unicodeScalars.contains { CharacterSet.alphanumerics.inverted.contains($0) }
        return hasLetter && hasDigit && hasSymbol
    }
}

@MainActor
enum PasteboardUtil {
    static func copyString(_ string: String) {
        AppState.shared.pasteboardMonitor.performInternalWrite {
            let pb = NSPasteboard.general
            pb.clearContents()
            pb.setString(string, forType: .string)
        }
    }

    static func copyImage(_ image: NSImage) {
        AppState.shared.pasteboardMonitor.performInternalWrite {
            let pb = NSPasteboard.general
            pb.clearContents()
            pb.writeObjects([image])
        }
    }

    /// Synthesize ⌘V. Ad-hoc 签名下 AX 布尔可能误报，因此优先尝试发送事件。
    static func paste() {
        let ok = PermissionHelper.accessibilityStatusOK
        if !ok {
            // 仍尝试一次；许多环境开关已开但 API 短暂误报
            postCommandV()
            // 若用户从未授权，提示去设置
            DispatchQueue.main.asyncAfter(deadline: .now() + 0.05) {
                if !PermissionHelper.accessibilityStatusOK {
                    PermissionHelper.requestAccessibilityPrompt()
                    ToastController.shared.show("若未粘贴成功：请确认辅助功能已授权并重启 zTools")
                }
            }
            return
        }
        postCommandV()
    }

    /// Close overlays, activate previous app, then paste after a short delay.
    static func pasteIntoPreviousApp(delay: TimeInterval = 0.15) {
        Task { @MainActor in
            AppState.shared.panelController.close()
            CommandPaletteController.shared.close()
            AppState.shared.activatePreviousApp()
            try? await Task.sleep(nanoseconds: UInt64(delay * 1_000_000_000))
            paste()
        }
    }

    private static func postCommandV() {
        let source = CGEventSource(stateID: .hidSystemState)
        let keyDown = CGEvent(keyboardEventSource: source, virtualKey: 0x09, keyDown: true)
        let keyUp = CGEvent(keyboardEventSource: source, virtualKey: 0x09, keyDown: false)
        keyDown?.flags = .maskCommand
        keyUp?.flags = .maskCommand
        keyDown?.post(tap: .cghidEventTap)
        keyUp?.post(tap: .cghidEventTap)
    }
}
